let currentBatchData = null;

function renderDeductions() {
    const select = document.getElementById("payrollBatchSelect");
    const batches = state.payrollBatches || [];
    if (batches.length === 0) {
        currentBatchData = null;
    }
    if (select) {
        const currentVal = select.value;
        select.innerHTML = '<option value="">Select Payroll Month</option>' + 
            batches.map(b => `<option value="${b.id}">${escapeHtml(b.payroll_month)} (${b.batch_number})</option>`).join('');
        if (currentVal && batches.find(b => String(b.id) === String(currentVal))) {
            select.value = currentVal;
        } else if (currentVal) {
            currentBatchData = null;
        }
    }
    
    const container = document.getElementById("payrollBatchContent");
    
    if (!currentBatchData) {
        container.innerHTML = `
            <div class="panel" style="padding: 40px; text-align: center; color: var(--muted);">
                ${batches.length > 0 ? 'Please select a Payroll Month from the dropdown above.' : 'No archived payroll reports available.'}
            </div>
        `;
        document.getElementById("exportBatchBtn").disabled = true;
        return;
    }

    document.getElementById("exportBatchBtn").disabled = false;

    const records = currentBatchData.records || [];
    const deductions = records.filter(r => r.record_type === 'Deduct');
    const waives = records.filter(r => r.record_type === 'Waive');
    const holds = records.filter(r => r.record_type === 'Hold');

    container.innerHTML = `
        <div class="mini-stats" style="margin-bottom: 18px; grid-template-columns: repeat(4, 1fr);">
            <article><span>Batch Number</span><strong style="font-size: 16px;">${escapeHtml(currentBatchData.batch.batch_number)}</strong></article>
            <article><span>Payroll Month</span><strong style="font-size: 16px;">${escapeHtml(currentBatchData.batch.payroll_month)}</strong></article>
            <article><span>Generated By</span><strong style="font-size: 16px;">${escapeHtml(currentBatchData.batch.generated_by)}</strong></article>
            <article><span>Total Recovery</span><strong class="text-red" style="font-size: 16px;">${formatCompactMoney(currentBatchData.batch.total_recovery_amount)}</strong></article>
        </div>

        <div class="panel">
          <div style="margin-bottom: 15px;">
            <h3 style="margin: 0;">Salary Deduction Register</h3>
          </div>
          <div class="table-wrap">
            <table>
              <thead><tr><th>Code</th><th>Name</th><th>Item</th><th>Qty</th><th>Rate</th><th>Amount</th><th>Remarks</th></tr></thead>
              <tbody>
                ${deductions.map(row => `
                    <tr>
                        <td>${text(row.employee_code)}</td>
                        <td>${text(row.employee_name)}</td>
                        <td>${text(row.item_name)}</td>
                        <td>${text(row.quantity)}</td>
                        <td>${formatCompactMoney(row.rate)}</td>
                        <td class="text-red">${formatCompactMoney(row.amount)}</td>
                        <td class="reason">${text(row.remarks)}</td>
                    </tr>
                `).join('') || `<tr><td colspan="7" class="empty">No deductions in this batch.</td></tr>`}
              </tbody>
            </table>
          </div>
        </div>

        <div class="panel">
          <div style="margin-bottom: 15px;">
            <h3 style="margin: 0;">Hold Register</h3>
          </div>
          <div class="table-wrap">
            <table>
              <thead><tr><th>Code</th><th>Name</th><th>Item</th><th>Qty</th><th>Remarks</th></tr></thead>
              <tbody>
                ${holds.map(row => `
                    <tr>
                        <td>${text(row.employee_code)}</td>
                        <td>${text(row.employee_name)}</td>
                        <td>${text(row.item_name)}</td>
                        <td>${text(row.quantity)}</td>
                        <td class="reason">${text(row.remarks)}</td>
                    </tr>
                `).join('') || `<tr><td colspan="5" class="empty">No holds in this batch.</td></tr>`}
              </tbody>
            </table>
          </div>
        </div>

        <div class="panel">
          <div style="margin-bottom: 15px;">
            <h3 style="margin: 0;">Waived Register</h3>
          </div>
          <div class="table-wrap">
            <table>
              <thead><tr><th>Code</th><th>Name</th><th>Item</th><th>Qty</th><th>Remarks</th></tr></thead>
              <tbody>
                ${waives.map(row => `
                    <tr>
                        <td>${text(row.employee_code)}</td>
                        <td>${text(row.employee_name)}</td>
                        <td>${text(row.item_name)}</td>
                        <td>${text(row.quantity)}</td>
                        <td class="reason">${text(row.remarks)}</td>
                    </tr>
                `).join('') || `<tr><td colspan="5" class="empty">No waives in this batch.</td></tr>`}
              </tbody>
            </table>
          </div>
        </div>
    `;
}

window.resetPayrollArchiveView = function() {
    currentBatchData = null;
    const select = document.getElementById("payrollBatchSelect");
    if (select) select.innerHTML = '<option value="">Select Payroll Month</option>';
    const container = document.getElementById("payrollBatchContent");
    if (container) {
        container.innerHTML = `
            <div class="panel" style="padding: 40px; text-align: center; color: var(--muted);">
                No archived payroll reports available.
            </div>
        `;
    }
    const exportButton = document.getElementById("exportBatchBtn");
    if (exportButton) exportButton.disabled = true;
};

document.getElementById("payrollBatchSelect")?.addEventListener("change", async (e) => {
    const batchId = e.target.value;
    if (!batchId) {
        currentBatchData = null;
        renderDeductions();
        return;
    }
    try {
        startProgress();
        currentBatchData = await window.uniformManager.getPayrollBatchData(batchId);
        stopProgress();
        renderDeductions();
    } catch(err) {
        stopProgress();
        showImportError(err.message);
    }
});

window.openGenerateBatchModal = function() {
    document.getElementById("generateBatchForm").reset();
    document.getElementById("generateBatchModal").classList.add("show");
};

window.closeGenerateBatchModal = function() {
    document.getElementById("generateBatchModal").classList.remove("show");
};

document.getElementById("generateBatchForm")?.addEventListener("submit", async (e) => {
    e.preventDefault();
    const fd = new FormData(e.currentTarget);
    const payload = {
        payroll_month: fd.get("payroll_month"),
        generated_by: fd.get("generated_by")
    };
    try {
        startProgress();
        const res = await window.uniformManager.generatePayrollBatch(payload);
        state = res.state;
        currentBatchData = await window.uniformManager.getPayrollBatchData(res.batchId);
        
        setTimeout(() => {
           const sel = document.getElementById("payrollBatchSelect");
           if (sel) sel.value = res.batchId;
        }, 100);

        closeGenerateBatchModal();
        stopProgress();
        render();
        toast("Payroll Batch generated successfully.");
    } catch(err) {
        stopProgress();
        showImportError(err.message);
    }
});

function getTodayDateStr() {
    return new Date().toISOString().split('T')[0];
}

async function triggerExcelExport(reportType) {
    if (!state) return toast("Data is not loaded yet.");
    
    let config = { headers: [], data: [], sheetName: "", filename: "" };
    const dateStr = getTodayDateStr();

    if (reportType === 'archivedBatch') {
        if (!currentBatchData) return toast("Please select a batch first.");
        
        config.headers = ["Record Type", "Employee Code", "Employee Name", "Item", "Quantity", "Rate", "Amount", "Remarks"];
        config.data = currentBatchData.records.map(r => [
            r.record_type, r.employee_code, r.employee_name, r.item_name, r.quantity, r.rate, r.amount, r.remarks
        ]);
        config.sheetName = "Archived Batch";
        config.filename = `Payroll_Batch_${currentBatchData.batch.batch_number}.xlsx`;
    } else if (reportType === 'pendingReview') {
        const pending = (state.reviews || []).filter(r => r.status === 'Pending');
        config.headers = ["Employee Code", "Employee Name", "Unit", "Item", "Issued Qty", "Allowed Qty", "Pending Qty"];
        config.data = pending.map(r => [
            r.employee_code, r.employee_name, r.unit, r.item_name, r.issued_qty, r.allowed_qty || 0, r.pending_qty
        ]);
        config.sheetName = "Pending Reviews";
        config.filename = `Pending_Review_Register_${dateStr}.xlsx`;
    } else if (reportType === 'history') {
        config.headers = ["Employee Code", "Employee Name", "Unit", "Godown", "Item", "Quantity", "Period", "Date Issued"];
        config.data = (state.uniformIssues || []).map(r => [
            r.employee_code, r.employee_name, r.unit, r.godown, r.item_name, r.quantity, r.issue_period_label, r.issued_at?.split('T')[0]
        ]);
        config.sheetName = "Employee History";
        config.filename = `Employee_History_${dateStr}.xlsx`;
    }

    if (config.data.length === 0) {
        return toast("No data available for export.");
    }

    try {
        startProgress();
        const res = await window.uniformManager.exportExcel(config);
        stopProgress();
        if (!res.canceled) toast("Excel exported successfully to: " + res.filePath);
    } catch (err) {
        stopProgress();
        showImportError("Export failed: " + err.message);
    }
}

document.addEventListener("click", (event) => {
    const exportBtn = event.target.closest("[data-export]");
    if (exportBtn) {
        triggerExcelExport(exportBtn.dataset.export);
    }
});
